### ISSUE TITLE
Is there a way to open this with a .exe file?

### ISSUE THREAD

**Issue by cmarabate** [tborychowski/github-browser#58]
It seems odd to me that an app would require you to open the directory in command prompt and start via npm start.

I know how to do all that but I don't see myself doing that every time I want to open the app. If it was able to open from an exe like every other app I've ever installed, I could then create a AutoHotkey Script to toggle it open and closed with a single hotkey. Then I would use it for sure!

**Comment by tborychowski** [comment]
Hi,
This requirement is only for development of the app.

There is no exe file because I don't have access to a windows machine to compile it and (at the time I worked on that app) it wasn't possible to do that on another platform.

You should be able to easily build an exe yourself though.
Unfortunately, I have no free time ATM to help you with this process.
Sorry about that.

**Comment by cmarabate** [comment]
Ahhh, okay. 

That is good to know I can build an exe for it. I will have to figure that out!

I should be able to do that using [Electron](https://www.electronjs.org/) right?

**Comment by tborychowski** [comment]
so this is the line that builds it for mac:
https://github.com/tborychowski/tim/blob/master/package.json#L14

you can run that script in terminal by typing:
```
npm run build
```
you need a similar line for windows. Maybe:
```
"gulp build && build --win"
```

**Comment by cmarabate** [comment]
Thanks, I appreciate the help!
